services:
  faas-engine:
    build: ./engine
    environment:
      - ENGINE_ID=${ENGINE_ID}
      - DB_HOST=faas-mariadb
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - faas-net
    depends_on:
      - faas-mariadb

  faas-scheduler:
    build: ./scheduler
    environment:
      - DB_HOST=faas-mariadb
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - CLEANUP_INTERVAL=${CLEANUP_INTERVAL}
      - DELETE_AFTER=${DELETE_AFTER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - faas-engine
    networks:
      - faas-net

  faas-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - faas-net

  faas-nginx:
    image: nginx:stable-alpine-perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - faas-engine
    networks:
      - faas-net

volumes:
  mariadb_data:

networks:
  faas-net:
    name: faas-net
    external: true
