services:
  faas-engine:
    build: .
    environment:
      - ENGINE_ID=${ENGINE_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - faas-net

  nginx:
    image: nginx:stable-alpine-perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - faas-engine
    networks:
      - faas-net

networks:
  faas-net:
    name: faas-net
    external: true
